[variables]

[settings]
  
  target = "tests-console"
  configuration = "debug"
  includePaths = ['./include']
  unitPaths = ['.', './GLPT', './GLPT/threads']
  libraryPaths = ['./lib', '/usr/local/lib']
  compiler = "/usr/local/lib/fpc/${LATEST}/${ARCH}"
  program = "./GLCanvas.pas"
  output = './output'
  executable = "./GLCanvas"
  symbols = ['PLATFORM_SDL']
  options = [
    "-vbr",
    "-vm6058" # hide "not inlined" warnings
  ]

[configuration.debug]

  options = ["-gw", "-godwarfcpp", "-Sa"]

[configuration.release]

  options = ["-Xs", "-O2"]

[target.tests-console]
  
  program = "./tests/test8.pas"
  executable = "./tests/ConsoleApp"

[target.tests-iphonesim]
  
  parent = "iphonesim"
  program = "./tests/test5.pas"
  executable = "./GLCanvas"